name: Test MySQL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql: [ '5.6', '5.7', '8.0' ]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql database: 'tests'
          mysql root password: 'pass'

      - uses: actions/checkout@v2

      - name: Test MySQL
        run: cd example && go test -v example
        env:
          GO111MODULE: on
          mysql_dsn: root:pass@tcp(127.0.0.1:3306)/tests?charset=utf8mb4&parseTime=True&loc=Local
