name: CURD Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'tests'
          mysql root password: 'pass'

      - uses: actions/checkout@v2

      - name: Test MySQL
        run: go test -v -race -covermode atomic -coverprofile=covprofile ./...
        env:
          GO111MODULE: on
          DSN: root:pass@tcp(127.0.0.1:3306)/tests?charset=utf8mb4&parseTime=True&loc=Local

      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github